config/routes.rb
InscEnus::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :events, :shallow => true do
    resources :teams
  end

  root :to => 'events#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/event.rb
class Event < ActiveRecord::Base

	has_many :teams

  	attr_accessible :active, :description, :maxperson, :name, :registration_ids

	validates :name, presence: true, length: {minimum: 3, maximum: 140}
	validates :description, presence: true
	validates :maxperson, presence: true
end

app/models/member.rb
#encoding: utf-8
class Member < ActiveRecord::Base
	attr_accessible :cpf, :email, :name, :phone, :rg

	validates :name, presence: true, length: {minimum: 3, maximum: 140}

	validates :cpf, presence: true, 
				:uniqueness => { :scope => @event, :message => "Cada integrante só pode se inscrever em um único time por evento" }

	validates :email, presence: true,
				:uniqueness => { :scope => @event, :message => "Cada integrante só pode se inscrever em um único time por evento" } 
				
	validates :rg, presence: true

	validates :phone, presence: true

	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :save
	
	before_save { |member| member.email = email.downcase }

	def formatted_email
		"#{@name} <#{@email}>"
	end
end

app/models/team.rb
#encoding: utf-8
class Team < ActiveRecord::Base
  
  belongs_to :event
  has_many :members

  attr_accessible :name, :members_attributes

  accepts_nested_attributes_for :members, :allow_destroy => true


  # Validations
  validate :limit_of_members

  validates :name, :uniqueness => {:scope => @team, :case_sensitive => false }
  
  def limit_of_members
    errors.add(:members, 'Excedido o número máximo de pessoas por time') if members.length > event.maxperson
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  respond_to :html
end

app/controllers/events_controller.rb
#encoding: utf-8

class EventsController < ApplicationController
  def index
    @events = Event.all

    respond_to do |format|
      format.html # chama -> index.html.erb
    end
  end

  def new
    @event = Event.new

    respond_to do |format|
      format.html # chama -> new.html.erb
    end
  end

  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Atração cadastrada com sucesso"}
      else
        format.html { render action: "new"}
      end
    end
  end

  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @atracao.update_attributes(params[:atracao])
        format.html { redirect_to @event, notice: 'Atração atualizada com sucesso.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/members_controller.rb
#encoding: utf-8

class MembersController < ApplicationController



end

app/controllers/teams_controller.rb
#encoding: utf-8

class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @event = Event.find(params[:event_id])
    @team = @event.teams.new
  end

  def edit
    @team = Team.find(params[:id])
    @event = @team.event
  end

  def create
    @event = Event.find(params[:event_id])
    @team = @event.teams.new(params[:team])
    
    if @team.save
      flash[:notice] = "ixi salvou"
      flash[:notice_class] = "class"
    else
      flash[:notice] = "ixi, deu merda"
      flash[:notice_class] = "class"
    end
    respond_with @team
  end

  def update
    @team = Team.find(params[:id])
    @team.update_attributes(params[:team])
    respond_with @team
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    respond_with @team
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :active, as: :boolean %>
  <%= f.input :maxperson %>

  <%= f.submit %>

  <td><%= link_to 'Atrações', events_path %></td>
<% end %>

app/views/events/edit.html.erb
<h1>Editar Atração</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h3>Selecione a atração na qual deseja inscrever-se</h3>

<div class="btn-group">
  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
    Selecione uma atração
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <% @events.each do |event| %>
      <li><%= link_to "#{event.name}", new_event_team_path(event) %></li>
    <% end %>
  </ul>
</div>

app/views/events/new.html.erb
<h1>Cadastrar Atração</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<h3><%= @event.name %></h3>
<p><%= @event.description %></p>
<p><%= @event.active %></p>
<b>Limite de Integrantes:</b><%= @event.maxperson %>
<br/>
<td><%= link_to 'Atrações', events_path %></td>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inscrições</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
</body>
</html>

app/views/members/_show.html.erb
<h1><%= member.name %></h1>
<p><%= member.email %></p>
<p><%= member.cpf %></p>
<p><%= member.rg %></p>
<p><%= member.phone %></p>